import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {LabService} from '../src/lab/service.js';
import {MailpitReader} from '../src/lab/mailpit.js';
const sourceRoot=fileURLToPath(new URL('../',import.meta.url));
async function fixture(t){const directory=await mkdtemp(join(tmpdir(),'cro-lab-'));t.after(()=>rm(directory,{recursive:true,force:true}));let now=Date.parse('2026-10-08T12:00:00Z');let messages=[];const options={dataDirectory:directory,sourceRoot,clock:()=>now,mailpit:{status:async()=>({configured:true,reachable:true}),messages:async()=>messages}};const lab=new LabService(options);await lab.initialize();const a=lab.catalogue.applications.find(a=>a.versions.length);const instance=await lab.createInstance({product:a.id,version:a.versions[0].version});return {lab,options,instance,setMessages:m=>messages=m,advance:ms=>now+=ms,message:(id,extra={})=>({ID:id,Created:new Date(now).toISOString(),From:{Address:'sender@example.invalid'},To:[{Address:'user@example.invalid'}],Subject:'Validation',...extra}),body:{instanceId:instance.id,recipient:'user@example.invalid',sender:'sender@example.invalid',subject:'Validation',mode:'mailpit'}};}
test('concurrent plans deduplicate and survive restart',async t=>{const {lab,options,instance}=await fixture(t);await Promise.all(Array.from({length:10},()=>lab.createInstance({product:instance.product,version:instance.version})));const restarted=new LabService(options);await restarted.initialize();assert.equal((await restarted.overview()).instances.length,1);});
test('baseline, recipient, sender and subject filter; no password success inferred',async t=>{const f=await fixture(t);f.setMessages([f.message('old')]);const c=await f.lab.createCheckpoint(f.body);f.advance(1000);f.setMessages([f.message('old'),f.message('wrong-sender',{From:{Address:'other@example.invalid'}}),f.message('wrong-recipient',{To:[{Address:'other@example.invalid'}]}),f.message('wrong-subject',{Subject:'Other'})]);assert.equal((await f.lab.inspect(c.id)).state,'awaiting_email');f.setMessages([f.message('candidate')]);const observed=await f.lab.inspect(c.id);assert.equal(observed.state,'ready_to_verify');assert.equal(observed.rotationVerified,false);assert.equal(observed.vaultUpdated,false);const publicData=JSON.stringify(await f.lab.overview());assert.ok(!publicData.includes('user@example.invalid'));assert.ok(!publicData.includes('sender@example.invalid'));assert.ok(!publicData.includes('candidate'));});
test('ambiguity, closure and manual acknowledgement remain unverified',async t=>{const f=await fixture(t);const c=await f.lab.createCheckpoint(f.body);f.advance(1000);f.setMessages([f.message('one'),f.message('two')]);assert.equal((await f.lab.inspect(c.id)).state,'ambiguous');await assert.rejects(f.lab.createCheckpoint(f.body));assert.equal((await f.lab.close({id:c.id})).state,'closed_unverified');const manual=await f.lab.createCheckpoint({...f.body,mode:'manual'});const ack=await f.lab.acknowledge({id:manual.id});assert.equal(ack.state,'ready_to_verify');assert.equal(ack.rotationVerified,false);});
test('expired checkpoints cannot be acknowledged',async t=>{const f=await fixture(t);const c=await f.lab.createCheckpoint({...f.body,mode:'manual',timeoutMinutes:1});f.advance(60000);assert.equal((await f.lab.acknowledge({id:c.id})).state,'expired');});
test('failed mailbox access does not create a checkpoint',async t=>{const f=await fixture(t);f.options.mailpit.messages=async()=>{throw new Error('unavailable');};await assert.rejects(f.lab.createCheckpoint(f.body));assert.equal(f.lab.state.checkpoints.length,0);});
test('Mailpit limits destinations, redirects, payload and pagination',async()=>{for(const url of ['https://example.com','http://localhost:8025','http://127.0.0.1:8025/path','http://user:pass@127.0.0.1:8025'])assert.throws(()=>new MailpitReader(url));let options;const m=new MailpitReader('http://127.0.0.1:8025',{fetchImpl:async(url,o)=>{options=o;return new Response(JSON.stringify({messages:[],total:501}));}});await assert.rejects(m.messages());assert.equal(options.redirect,'error');m.fetch=async()=>new Response('x'.repeat(1024*1024+1));await assert.rejects(m.messages(),/volumineuse/);m.fetch=async()=>new Response(JSON.stringify({messages:[],total:1}));await assert.rejects(m.messages(),/incohérente/);});
