import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,readdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';
import {SiteAuthGuard,authenticationSite} from '../src/core/site-auth-guard.js';
async function fixture(t){const directory=await mkdtemp(join(tmpdir(),'cro-auth-'));t.after(()=>rm(directory,{recursive:true,force:true}));return {directory,guard:new SiteAuthGuard(directory)};}
test('one rejection blocks every further attempt, including another account and restarted process',async t=>{const {directory,guard}=await fixture(t);let calls=0;await assert.rejects(guard.attempt('https://EXAMPLE.invalid/login',async()=>{calls++;return false;}),/rejected/);await assert.rejects(new SiteAuthGuard(directory).attempt('http://example.invalid.:8080/another-account',async()=>{calls++;return true;}),/locked/);assert.equal(calls,1);const module=new URL('../src/core/site-auth-guard.js',import.meta.url).href;const code=`import {SiteAuthGuard} from ${JSON.stringify(module)};try{await new SiteAuthGuard(process.argv[1]).attempt('https://example.invalid',async()=>{process.stdout.write('REQUEST_SENT');return true;});process.exitCode=2;}catch(e){if(e.message!=='site_authentication_locked')process.exitCode=3;}`;const p=spawnSync(process.execPath,['--input-type=module','-e',code,directory],{encoding:'utf8'});assert.equal(p.status,0);assert.equal(p.stdout,'');const content=await readFile(join(directory,(await readdir(directory))[0]),'utf8');assert.ok(!content.includes('password'));});
test('uncertain result or thrown network error locks the site',async t=>{const {guard}=await fixture(t);await assert.rejects(guard.attempt('https://example.invalid',async()=>{throw new Error('timeout');}));await assert.rejects(guard.attempt('https://example.invalid',async()=>true),/locked/);});
test('concurrent attempts are serialized across guard instances',async t=>{const {directory,guard}=await fixture(t);let release,entered;const ready=new Promise(r=>entered=r);const first=guard.attempt('https://example.invalid',async()=>{entered();await new Promise(r=>release=r);return false;});const rejected=assert.rejects(first,/rejected/);await ready;await assert.rejects(new SiteAuthGuard(directory).attempt('https://example.invalid',async()=>true),/locked/);release();await rejected;});
test('success permits later verification, while another site is independent',async t=>{const {guard}=await fixture(t);await guard.attempt('https://example.invalid',async()=>true);await guard.attempt('https://example.invalid',async()=>true);await assert.rejects(guard.attempt('https://example.invalid',async()=>false));await guard.attempt('https://different.invalid',async()=>true);});
test('normalization cannot vary by scheme, path, port, trailing dot or account',()=>{assert.equal(authenticationSite('http://EXAMPLE.invalid.:8000/a'),'example.invalid');assert.throws(()=>authenticationSite('https://user:pass@example.invalid'));assert.throws(()=>new SiteAuthGuard());});
